create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  namn text not null,
  hole1 integer not null,
  hole2 integer not null,
  hole3 integer not null,
  hole4 integer not null,
  hole5 integer not null,
  hole6 integer not null,
  hole7 integer not null,
  hole8 integer not null,
  hole9 integer not null,
  totalt integer not null
);

alter table public.scores enable row level security;

create policy "Alla kan läsa scores"
on public.scores
for select
to anon
using (true);

create policy "Alla kan lägga till scores"
on public.scores
for insert
to anon
with check (true);
